name: Tag
on:
  push:
    paths:
      - 'pyproject.toml'
    branches:
      - 'master'
      - '*.x'
  pull_request:
    paths:
      - 'pyproject.toml'
    branches:
      - 'master'
      - '*.x'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: True
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Initial dock-cli
        run: make clean init
      - name: Create tag
        run: make create-tag
      - name: Push tag
        if: github.event_name == 'push'
        run: make push-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean dock-cli
        if: always()
        run: make clean
