name: Test
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.12', python: '3.12', os: ubuntu-latest}
          - {name: '3.11', python: '3.11', os: ubuntu-latest}
          - {name: '3.10', python: '3.10', os: ubuntu-latest}
          - {name: '3.9', python: '3.9', os: ubuntu-latest}
          - {name: '3.8', python: '3.8', os: ubuntu-latest}
          - {name: '3.7', python: '3.7', os: ubuntu-latest}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Helm
        uses: azure/setup-helm@v4.1.0
      - name: Initial dock-cli
        run: make clean init list
      - name: Test dock-cli
        run: make test
      - name: Clean dock-cli
        run: make clean
