name: Test
on:
  push:
    branches:
      - 'master'
      - '*.x'
  pull_request:
    branches:
      - 'master'
      - '*.x'
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: 'Python 3.13', python: '3.13-dev', os: ubuntu-latest}
          - {name: 'Python 3.12', python: '3.12', os: ubuntu-latest}
          - {name: 'Python 3.11', python: '3.11', os: ubuntu-latest}
          - {name: 'Python 3.10', python: '3.10', os: ubuntu-latest}
          - {name: 'Python 3.9', python: '3.9', os: ubuntu-latest}
          - {name: 'Python 3.8', python: '3.8', os: ubuntu-latest}
          - {name: 'PyPy 3.10', python: 'pypy3.10', os: ubuntu-latest}
          - {name: 'PyPy 3.9', python: 'pypy3.9', os: ubuntu-latest}
          - {name: 'macOS', python: '3.12', os: macos-latest}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Helm
        uses: azure/setup-helm@v4.1.0
      - name: Initial dock-cli
        run: make clean init list
      - name: Test dock-cli
        run: make test
      - name: Clean dock-cli
        if: always()
        run: make clean
